---
# Tasks to install MongoDB

- name: Add apt key
  tags: install
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EA312927

- name: Add MongoDB repository
  tags: install
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
    filename: 'mongodb-org-3.2'

- name: Install package
  tags: install
  apt:
    name: mongodb-org
    update_cache: yes
    state: present

- name: enable mongod service
  tags: install
  systemd: name=mongod enabled=yes
