---
# tasks file for db

- name: Show the environment this host belongs to
  debug:
    msg: "The host is in {{ env }} environment!"

- name: Change MongoDB config file
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    mode: 0644
  notify: restart mongod
