---
- name: Install MongoDB
  hosts: all
  become: true

  tasks:
    - name: Add apt key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: EA312927

    - name: Add MongoDB repository
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
        filename: 'mongodb-org-3.2'

    - name: Install package
      apt:
        name: mongodb-org
        update_cache: yes
        state: present

    - name: enable mongod service
      systemd: name=mongod enabled=yes
