---
- name: Deploy the Reddit application
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 10.132.0.4
  
  tasks:
    - name: Fetch the latest version of the application code from GitHub
      git:
        repo: 'https://github.com/Otus-DevOps-2017-11/reddit.git'
        dest: /home/appuser/reddit
        version: monolith
      tags: deploy-tag
      notify: restart puma
    
    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit
      tags: deploy-tag
    
    - name: Change MongoDB config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags: db-tag
      notify: restart mongod
      
    - name: Copy env variables file (DB config)
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
      tags: app-tag
      
    - name: Copy Puma server unit file
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag
      notify: reload puma
      
    - name: enable puma service
      become: true
      systemd: name=puma state=enabled
      tags: app-tag
  
  handlers:
  - name: restart mongod
    become: true
    service: name=mongod state=restarted
    
  - name: reload puma
    become: true
    systemd: name=puma state=reloaded
    
  - name: restart puma
    become: true
    systemd: name=puma state=restarted
