---
- name: Config the DB hosts
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0
  
  tasks:
    - name: Change MongoDB config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod
  
  handlers:
  - name: restart mongod
    service: name=mongod state=restarted


- name: Config the App hosts
  hosts: app
  tags: app-tag
  become: true
  vars:
    db_host: 10.132.0.4
  
  tasks:
    - name: Copy env variables file (DB config)
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser
      
    - name: Copy Puma server unit file
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma
      
    - name: enable puma service
      systemd: name=puma state=enabled
  
  handlers:
  - name: reload puma
    systemd: name=puma state=reloaded
    

- name: Deploy the latest App version
  hosts: app
  tags: deploy-tag
  
  tasks:
    - name: Fetch the latest version of the application code from GitHub
      git:
        repo: 'https://github.com/Otus-DevOps-2017-11/reddit.git'
        dest: /home/appuser/reddit
        version: monolith
      notify: restart puma
    
    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit
      
  handlers:
  - name: restart puma
    become: true
    systemd: name=puma state=restarted